keys:
  - DEPLOYER_KEY
  - ETHERSCAN_API_KEY
  - RPC_URL
  - PINATA_JWT

profiles:
  sepolia:
    DEPLOYER_KEY: dev/DEPLOYER_KEY
  zksync-sepolia:
    DEPLOYER_KEY: dev/DEPLOYER_KEY
  default:
    PINATA_JWT: ?=
