parser: '@typescript-eslint/parser'
parserOptions:
  project: './packages/subgraph/tsconfig.json'

# Custom eslint settings for the subgraph can be defined here
ignorePatterns:
  - imported/
  - generated/
  - tests/
  - extended-schema.ts

rules: {'@typescript-eslint/ban-types': ['error', {'types': {'BigInt': false}}]}
